name: Lint on Pull Request

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node JS
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.0

      - name: Checkout to server
        uses: cd ./server

      - name: Install dependencies for server
        run: npm ci

      - name: Run ESLint for server
        run:  npm run lint

      - name: Checkout to client
        uses: cd ./client

      - name: Install dependencies for client
        run: npm ci

      - name: Run ESLint for client
        run: npm run eslint

      - name: Run Stylelint for client
        run: npm run stylelint
